
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech 
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# AEM-DR
modbus:
  - name: "AED-DR Multi-loop Energy meter"  # 自定義 Modbus 設備名稱
    type: tcp
    host: 192.168.1.253
    port: 502
    sensors:
      - name: "loop1_current"  # 電流
        slave: 1
        unique_id: "loop1_current"
        unit_of_measurement: "A"  # 電流單位
        address: 0x02   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop2_current"  # 電流
        slave: 1
        unique_id: "loop2_current"
        unit_of_measurement: "A"  # 電流單位
        address: 0x03   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop3_current"  # 電流
        slave: 1
        unique_id: "loop3_current"
        unit_of_measurement: "A"  # 電流單位
        address: 0x04   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop4_current"  # 電流
        slave: 1
        unique_id: "loop4_current"
        unit_of_measurement: "A"  # 電流單位
        address: 0x05   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop5_current"  # 電流
        slave: 1
        unique_id: "loop5_current"
        unit_of_measurement: "A"  # 電流單位
        address: 0x06   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop1_total_active_energy"  # 功率
        slave: 1
        unique_id: "loop1_total_active_power"
        unit_of_measurement: "kW"  # 功率單位
        address: 0x27   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop2_total_active_energy"  # 功率
        slave: 1
        unique_id: "loop2_total_active_power"
        unit_of_measurement: "kW"  # 功率單位
        address: 0x2B   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop3_total_active_power"  # 功率
        slave: 1
        unique_id: "loop3_total_active_power"
        unit_of_measurement: "kW"  # 功率單位
        address: 0x2F   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop4_total_active_power"  # 功率
        slave: 1
        unique_id: "loop4_total_active_power"
        unit_of_measurement: "kW"  # 功率單位
        address: 0x33   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop5_total_active_power"  # 功率
        slave: 1
        unique_id: "loop5_total_active_power"
        unit_of_measurement: "kW"  # 功率單位
        address: 0x37   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop1_total_power"  # 度數
        slave: 1
        unique_id: "loop1_total_power"
        unit_of_measurement: "kWh"  # 度數單位
        state_class: total_increasing
        address: 0x2A   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop2_total_power"  # 度數
        slave: 1
        unique_id: "loop2_total_power"
        unit_of_measurement: "kWh"  # 度數單位
        state_class: total_increasing
        address: 0x2E   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop3_total_power"  # 度數
        slave: 1
        unique_id: "loop3_total_power"
        unit_of_measurement: "kWh"  # 度數單位
        state_class: total_increasing
        address: 0x32   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop4_total_power"  # 度數
        slave: 1
        unique_id: "loop4_total_power"
        unit_of_measurement: "kWh"  # 度數單位
        state_class: total_increasing
        address: 0x36   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60
      - name: "loop5_total_power"  # 度數
        slave: 1
        unique_id: "loop5_total_power"
        unit_of_measurement: "kWh"  # 度數單位
        state_class: total_increasing
        address: 0x3A   # 寄存器位址
        input_type: holding
        data_type: int16  # 資料格式（根據設備手冊選擇）
        scale: 0.001  # 如果數據需要縮放，設定比例，例如 0.1 代表數據需除以 10
        precision: 3  # 顯示的小數位數
        scan_interval : 60        
        
        
